name: Create Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"

permissions:
  contents: write
  pull-requests: write

env:
  PLUGIN_JSON: "0.0.1"
  TAG_EXISTS: false
  PLUGIN_NAME: "Nostradamus"

jobs:
          tag: "${{fromJson(env.PLUGIN_JSON).version}}"
            ${{ github.event.head_commit.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
